ALTER TABLE CATEGORIAS MODIFY (CAT_CODIGO NOT NULL);
ALTER TABLE CATEGORIAS MODIFY(CAT_DESCRIPCION NOT NULL);
ALTER TABLE CATEGORIAS MODIFY (CAT_CODIGO NUMBER(6,0) DEFAULT 0);

ALTER TABLE MEDIDAS MODIFY (MED_CODIGO NOT NULL);
ALTER TABLE MEDIDAS MODIFY (MED_DESCRIPCION VARCHAR(30)); --ANTES ERA VARHCAR(20)
ALTER TABLE MEDIDAS MODIFY (MED_CODIGO NUMBER(6,0) DEFAULT 0);

ALTER TABLE ARTICULOS MODIFY (ART_CODIGO NOT NULL);
ALTER TABLE ARTICULOS DROP COLUMN ART_MARCA;        --ELIMINA UNA COLUMNA
ALTER TABLE ARTICULOS ADD ART_MARCA VARCHAR(30);    --AGREGA UNA COLUMNA
ALTER TABLE ARTICULOS MODIFY (ART_CODIGO NUMBER(6,0) DEFAULT 0);