CREATE TABLE CATEGORIAS
(
    CAT_CODIGO      INT,
    CAT_DESCRIPCION VARCHAR(30)
);

CREATE TABLE MEDIDAS
(
    MED_CODIGO NUMBER(3,0),
    MED_ABREVIATURA VARCHAR(3),
    MED_DESCRIPCION VARCHAR(20)
);


--NUMBER (3,0) => DEFINE LA PRESICI�N : 3 DIGITOS PARA LA PARTE ENTERA, O PARA LA PARTE DECIMAL
-- SI NO ES DEFINIDA LA PRESICI�N, ORACLE LO INTERPRETAR� CON SUS VALORES POR DEFECTO

CREATE TABLE ARTICULOS
(
    ART_CODIGO NUMBER(5,0),
    ART_DESCRIPCION VARCHAR(50),
    ART_MARCA VARCHAR(30),
    MED_CODIGO NUMBER(3,0),
    CAT_CODIGO INT,
    ART_FECHA_INGRESO DATE,
    ART_STOCK DECIMAL(10,2)
);